# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f328bcda2d0f531aa424be7508c21ca49899206bd16bbe1440b52206b7ff40327b3fbca67f21c7c0d6cfdd6f7b8c4f5ee39aa7d92bd4795ef2e1edbc0ba5d02

test:
  secret_key_base: c20cc279699448cf5551b41a497bc743ea74642b349d91291e8f1a650a013cd7f8d7756b4e996c61d3f8b386aa56f999deb860b851553be6160130dee42e996c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
