Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.network :forwarded_port, guest: 80, host: 8800
  config.vm.network :forwarded_port, guest: 81, host: 8801
  config.vm.network :forwarded_port, guest: 82, host: 8802
  config.vm.network :forwarded_port, guest: 83, host: 8803
  config.vm.network :forwarded_port, guest: 84, host: 8804
  config.vm.network :forwarded_port, guest: 85, host: 8805
  config.vm.network :forwarded_port, guest: 86, host: 8806
  config.vm.network :forwarded_port, guest: 87, host: 8807
end
