Vagrant.configure(2) do |config|
  config.vm.box_download_checksum_type = "sha256"
  config.vm.box_download_checksum = "01234567890"
  config.vm.box = "http://boxes.gajdaw.pl/apache/apache-v0.3.3.box"
end
