Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.synced_folder "./some/dir/first", "/first", create: true
  config.vm.synced_folder "./some/dir/second", "/second", create: true
end

